# Package Overview
package_name: classification_model

# Data Files
raw_data_file: raw.csv
training_data_file: train.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (sale price)
target: survived

pipeline_name: classification_model
pipeline_save_file: classification_model_output_v

features:
  - pclass
  - sex
  - age
  - sibsp
  - parch
  - fare
  - cabin
  - embarked
  - title  # computed from name in data_manager.py/pre_pipeline_preparation()

# set train/test split
test_size: 0.1

# to set the random seed
random_state: 0

unused_fields:
  - name
  - ticket
  - boat
  - body
  - home.dest

numerical_vars:
  - age
  - fare

categorical_vars:
  - sex
  - cabin
  - embarked
  - title

cabin_vars:
  - cabin